const $=s=>document.querySelector(s),empty=$("#empty"),friend=$("#friend"),friends=$("#friends"),chat=$("#chat"),toast=$("#toast"),music=$("#music");
function say(t){toast.textContent=t;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2200)}
function showLogin(){ $("#registerCard").classList.add("hidden");$("#loginCard").classList.remove("hidden") }
setTimeout(()=>{$("#intro").classList.add("out");setTimeout(()=>{$("#intro").classList.add("hidden");$("#auth").classList.remove("hidden")},600)},2300);
$("#eye").onclick=()=>{$("#loginPass").type=$("#loginPass").type==="password"?"text":"password"};
$("#showRegister").onclick=()=>{$("#loginCard").classList.add("hidden");$("#registerCard").classList.remove("hidden")};
$("#backLogin").onclick=showLogin;
$("#forgot").onclick=()=>say("A recuperação por e-mail será conectada quando o servidor online estiver pronto.");
$("#google").onclick=()=>say("O login Google será conectado quando o sistema online estiver pronto.");
$("#registerBtn").onclick=()=>{let u=$("#regUser").value.trim(),e=$("#regEmail").value.trim().toLowerCase(),p=$("#regPass").value,c=$("#regConfirm").value;if(u.length<3)return say("O nome precisa ter pelo menos 3 caracteres");if(!e.includes("@")||!e.split("@")[1]?.includes("."))return say("Digite um e-mail válido");if(p.length<6)return say("A senha precisa ter pelo menos 6 caracteres");if(p!==c)return say("As senhas não coincidem");if(!$("#terms").checked)return say("Aceite os termos para continuar");localStorage.setItem("nexusMobileUser",u);localStorage.setItem("nexusMobileEmail",e);localStorage.setItem("nexusMobilePass",p);$("#loginUser").value=e;showLogin();say("✓ Conta criada com sucesso!")};
function openLegal(title,body){$("#legalTitle").textContent=title;$("#legalBody").textContent=body;$("#legal").classList.remove("hidden")} $("#legalOk").onclick=()=>$("#legal").classList.add("hidden");
$("#termsBtn").onclick=()=>openLegal("Termos de Serviço","Use o NEXUS de forma responsável. Não utilize o serviço para atividades ilegais, fraude, assédio, invasão de contas, conteúdo malicioso ou ações que prejudiquem outros usuários.\n\nSua conta e suas credenciais devem ser mantidas em segurança. Recursos podem mudar durante o desenvolvimento.");
$("#privacyBtn").onclick=()=>openLegal("Política de Privacidade","Na versão atual, o cadastro mobile de teste fica salvo neste navegador/dispositivo. Não compartilhe sua senha. Quando a infraestrutura online for adicionada, esta política deverá ser atualizada para explicar o tratamento dos dados.");
function enter(){let id=$("#loginUser").value.trim().toLowerCase(),p=$("#loginPass").value,u=localStorage.getItem("nexusMobileUser"),e=localStorage.getItem("nexusMobileEmail"),rp=localStorage.getItem("nexusMobilePass");if(!u)return say("Crie uma conta primeiro");if((id!==u.toLowerCase()&&id!==e)||p!==rp)return say("Usuário/e-mail ou senha incorretos");music.pause();$("#auth").classList.add("hidden");$("#welcomeText").textContent="BEM-VINDO À NEXUS, "+u.toUpperCase();$("#welcome").classList.remove("hidden");setTimeout(()=>{$("#welcome").classList.add("out");setTimeout(()=>{$("#welcome").classList.add("hidden");$("#app").classList.remove("hidden")},550)},2200)}
$("#loginBtn").onclick=enter;$("#loginPass").addEventListener("keydown",e=>{if(e.key==="Enter")enter()});
function fmt(s){if(!isFinite(s))return"0:00";return Math.floor(s/60)+":"+String(Math.floor(s%60)).padStart(2,"0")}
$("#play").onclick=async()=>{if(music.paused){try{await music.play()}catch(e){say("Toque no play para iniciar a música")}}else music.pause()};
music.onplay=()=>$("#play").textContent="Ⅱ";music.onpause=()=>$("#play").textContent="▶";music.onloadedmetadata=()=>{$("#progress").max=Math.floor(music.duration)||0;$("#dur").textContent=fmt(music.duration)};music.ontimeupdate=()=>{$("#progress").value=Math.floor(music.currentTime);$("#cur").textContent=fmt(music.currentTime)};$("#progress").oninput=e=>music.currentTime=+e.target.value;$("#volume").onclick=()=>{music.muted=!music.muted;$("#volume").textContent=music.muted?"🔇":"🔊"};music.volume=.24;
$("#add").onclick=()=>{let n=$("#friendName").value.trim();if(n.toLowerCase()==="nexus_teste"){empty.classList.add("hidden");friend.classList.remove("hidden");localStorage.setItem("nexusFriend","1");say("NEXUS_Teste adicionado")}else say("Usuário não encontrado")};if(localStorage.getItem("nexusFriend")){empty.classList.add("hidden");friend.classList.remove("hidden")}friend.onclick=()=>{friends.classList.add("hidden");chat.classList.remove("hidden")};$("#back").onclick=()=>{chat.classList.add("hidden");friends.classList.remove("hidden")};function send(){let i=$("#message"),t=i.value.trim();if(!t)return;let b=document.createElement("div");b.className="bubble";b.textContent=t;$("#messages").appendChild(b);i.value="";$("#messages").scrollTop=$("#messages").scrollHeight}$("#send").onclick=send;$("#message").addEventListener("keydown",e=>{if(e.key==="Enter")send()});